### ISSUE TITLE
New generated type signatures are overly general and cause type errors

### ISSUE THREAD

**Issue by glguy** [simonmar/happy#104] opened 2017-09-11 16:58 UTC
Since version 1.19.5 happy now add type signatures to the generated parser source file. These signatures can be too general and introduce type-errors into previous accepted parsers.

I haven't pinned down what specifically is triggering this bug, but you can reproduce it by trying to build [cryptol-2.5.0](https://hackage.haskell.org/package/cryptol-2.5.0)

Cryptol makes use of the parameterized rules in happy, I'm going to explore if using these leads to the bug surfacing.

In the meantime, is there a flag I can use to disable these new type signatures?

**Comment by harpocrates** [comment] 2017-09-11 17:08
I think this is a duplicate of https://github.com/simonmar/happy/issues/94. The workaround is to add type signatures on _all_ productions.

**Comment by harpocrates** [comment] 2017-09-11 17:13
In your case, you are only missing a signature on `ipat`. I can get Cryptol to build by adding that signature back:

    ipat                           :: { Pattern PName }
      : ipat '#' ipat                 { at ($1,$3) $ PSplit $1 $3 }
      | apat                          { $1                        }

**Comment by simonmar** [comment] 2017-09-14 07:48
Thanks for reporting - closing as dup of #94

**Closed by simonmar** 2017-09-14 07:48 UTC
